trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Packer 
    variables:
      - group: vg
    displayName: Packer Image Build
    jobs:
      - job: Packer_Image_Build
        displayName: Packer Image Build
        steps:
        - task: CmdLine@2
          inputs: 
            script: 'packer build -var="client_secret=$(client-secret)" -var-file="variable.pkrvars.hcl" iis.json.pkr.hcl'
            workingDirectory: '$(Build.SourcesDirectory)'