subnetname = "Subnet_1"
vnetname = "Vnet_1"
resource_group_name ="Resource_Group_1"
location ="Central India"
vnet_address_space =["10.0.0.0/16"]
subnet_address = ["10.0.1.0/24"]
sr= "Securityrule_1"
security_group_name = "NSG_1"
priority = 100
name="my_image"
vmname = "vm1"
#VMIP = "VMIP"
nic= "NIC_1"
# lbname = "Load_Balancer_Shivani"
# bepool = "BackEndAddressPool"
packer_resource_group_name= "myPackerGroup"
packer_image_name = "myPackerImage1"
# pip= "public_ip"
machine_type = "private"
