subnetname = "Subnet_1"
vnetname = "Vnet_1"
resource_group_name ="Resource_Group_1"
location ="Central India"
# vnet_address_space =["10.1.0.0/16"]
# subnet_address = ["10.0.1.0/24"]
# sr= "Securityrule_1"
# security_group_name = "NSG_1"
# priority = 100
#vmssname = "vs1"
vmname = "VM_1"
# packer_resource_group_name= "Resource_Group_1_Image"
# packer_image_name = "1PackerImage"
# lbname = "Load_Balancer_1"
nic= "NIC_1"
#bepool = "BackEndAddressPool"
#VMIP = "VMIP"
machine_type= "private"
